"""first load

Revision ID: 0e48a9764b6a
Revises:
Create Date: 2024-10-16 22:03:54.638689

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e48a9764b6a'
down_revision: str = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hub_leagues',
        sa.Column('hk', sa.String(), nullable=False, comment='Hash Key for hub business key'),
        sa.Column('bk', sa.String(), nullable=True, comment='Business Key (league)'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('hk', name=op.f('pk_hub_leagues')),
        schema='main',
    )
    op.create_index(op.f('ix_main_hub_leagues_bk'), 'hub_leagues', ['bk'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_leagues_hk'), 'hub_leagues', ['hk'], unique=True, schema='main')
    op.create_table(
        'hub_matches',
        sa.Column('hk', sa.String(), nullable=False, comment='Hash Key for hub business key'),
        sa.Column('bk_match_country', sa.String(), nullable=True, comment='Business Key (country)'),
        sa.Column('bk_match_league', sa.String(), nullable=True, comment='Business Key (league)'),
        sa.Column('bk_match_season', sa.String(), nullable=True, comment='Business Key (season)'),
        sa.Column('bk_match_home_team', sa.String(), nullable=True, comment='Business Key (home team)'),
        sa.Column('bk_match_away_team', sa.String(), nullable=True, comment='Business Key (away team)'),
        sa.Column('bk_match_date', sa.String(), nullable=True, comment='Business Key (match date)'),
        sa.Column('bk_match_time', sa.String(), nullable=True, comment='Business Key (match time)'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('hk', name=op.f('pk_hub_matches')),
        schema='main',
    )
    op.create_index(op.f('ix_main_hub_matches_bk_match_away_team'), 'hub_matches', ['bk_match_away_team'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_matches_bk_match_country'), 'hub_matches', ['bk_match_country'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_matches_bk_match_date'), 'hub_matches', ['bk_match_date'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_matches_bk_match_home_team'), 'hub_matches', ['bk_match_home_team'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_matches_bk_match_league'), 'hub_matches', ['bk_match_league'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_matches_bk_match_season'), 'hub_matches', ['bk_match_season'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_matches_bk_match_time'), 'hub_matches', ['bk_match_time'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_matches_hk'), 'hub_matches', ['hk'], unique=True, schema='main')
    op.create_table(
        'hub_seasons',
        sa.Column('hk', sa.String(), nullable=False, comment='Hash Key for hub business key'),
        sa.Column('bk', sa.String(), nullable=True, comment='Business Key (season)'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('hk', name=op.f('pk_hub_seasons')),
        schema='main',
    )
    op.create_index(op.f('ix_main_hub_seasons_bk'), 'hub_seasons', ['bk'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_seasons_hk'), 'hub_seasons', ['hk'], unique=True, schema='main')
    op.create_table(
        'hub_teams',
        sa.Column('hk', sa.String(), nullable=False, comment='Hash Key for hub business key'),
        sa.Column('bk', sa.String(), nullable=True, comment='Business Key (team)'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('hk', name=op.f('pk_hub_teams')),
        schema='main',
    )
    op.create_index(op.f('ix_main_hub_teams_bk'), 'hub_teams', ['bk'], unique=False, schema='main')
    op.create_index(op.f('ix_main_hub_teams_hk'), 'hub_teams', ['hk'], unique=True, schema='main')
    op.create_table(
        'lnk_matches',
        sa.Column('hk', sa.String(), nullable=False, comment='Hash Key for hub business key'),
        sa.Column('hk_match_home_team', sa.String(), nullable=False, comment='Hash Key for hk_match_home_team'),
        sa.Column('hk_match_away_team', sa.String(), nullable=False, comment='Hash Key for hk_match_away_team'),
        sa.Column('hk_match_league', sa.String(), nullable=False, comment='Hash Key for hk_match_league'),
        sa.Column('hk_match_season', sa.String(), nullable=False, comment='Hash Key for hk_match_season'),
        sa.Column('hk_match_country', sa.String(), nullable=False, comment='Hash Key for hk_match_country'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('hk', name=op.f('pk_lnk_matches')),
        schema='main',
    )
    op.create_index(op.f('ix_main_lnk_matches_hk'), 'lnk_matches', ['hk'], unique=False, schema='main')
    op.create_index(op.f('ix_main_lnk_matches_hk_match_away_team'), 'lnk_matches', ['hk_match_away_team'], unique=False, schema='main')
    op.create_index(op.f('ix_main_lnk_matches_hk_match_country'), 'lnk_matches', ['hk_match_country'], unique=False, schema='main')
    op.create_index(op.f('ix_main_lnk_matches_hk_match_home_team'), 'lnk_matches', ['hk_match_home_team'], unique=False, schema='main')
    op.create_index(op.f('ix_main_lnk_matches_hk_match_league'), 'lnk_matches', ['hk_match_league'], unique=False, schema='main')
    op.create_index(op.f('ix_main_lnk_matches_hk_match_season'), 'lnk_matches', ['hk_match_season'], unique=False, schema='main')
    op.create_table(
        'monitor_logs',
        sa.Column('unique_id', sa.String(), nullable=False),
        sa.Column('ulid_thread', sa.String(length=26), nullable=True, comment='ULID thread identifier'),
        sa.Column('source', sa.String(length=50), nullable=True, comment='Name of the function logging the process'),
        sa.Column('process', sa.String(length=50), nullable=True, comment='Name of the process that is running'),
        sa.Column('status', sa.String(length=30), nullable=True, comment='Process status: started, finished, or error'),
        sa.Column('started_at', sa.TIMESTAMP(), nullable=True, comment='Timestamp when the process started'),
        sa.Column('finished_at', sa.TIMESTAMP(), nullable=True, comment='Timestamp when the process finished'),
        sa.Column('duration', sa.Float(), nullable=True, comment='Duration between start and finish'),
        sa.Column('memory_usage', sa.Float(), nullable=True, comment='Memory used in MB'),
        sa.Column('execution_time', sa.Float(), nullable=True, comment='Execution time in seconds'),
        sa.Column('cpu_time', sa.Float(), nullable=True, comment='CPU time used in seconds'),
        sa.Column('cpu_time_ratio', sa.Float(), nullable=True, comment='Calculate the ratio cpu_time_used / execution_time'),
        sa.Column('error_message', sa.String(), nullable=True, comment='Error message if any error occurred'),
        sa.PrimaryKeyConstraint('unique_id', name=op.f('pk_monitor_logs')),
        schema='main',
    )
    op.create_index(op.f('ix_main_monitor_logs_process'), 'monitor_logs', ['process'], unique=False, schema='main')
    op.create_index(op.f('ix_main_monitor_logs_source'), 'monitor_logs', ['source'], unique=False, schema='main')
    op.create_index(op.f('ix_main_monitor_logs_ulid_thread'), 'monitor_logs', ['ulid_thread'], unique=False, schema='main')
    op.create_table(
        'sat_matches_core_results',
        sa.Column('ulid', sa.String(), nullable=False, comment='ULID id for row'),
        sa.Column('hk_hub', sa.String(), nullable=True, comment='Hash Key for hub business key'),
        sa.Column('fthg', sa.Float(), nullable=False, comment='Full time home goals'),
        sa.Column('ftag', sa.Float(), nullable=False, comment='Full time away goals'),
        sa.Column('ftr', sa.Float(), nullable=False, comment='Full time result'),
        sa.Column('hthg', sa.Float(), nullable=True, comment='Half time home goals'),
        sa.Column('htag', sa.Float(), nullable=True, comment='Half time away goals'),
        sa.Column('htr', sa.Float(), nullable=True, comment='Half time result'),
        sa.Column('hash_diff', sa.String(), nullable=True, comment='Hash of row'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('ulid', name=op.f('pk_sat_matches_core_results')),
        schema='main',
    )
    op.create_index(op.f('ix_main_sat_matches_core_results_hash_diff'), 'sat_matches_core_results', ['hash_diff'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_core_results_hk_hub'), 'sat_matches_core_results', ['hk_hub'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_core_results_ulid'), 'sat_matches_core_results', ['ulid'], unique=False, schema='main')
    op.create_table(
        'sat_matches_core_statistics',
        sa.Column('ulid', sa.String(), nullable=False, comment='ULID id for row'),
        sa.Column('hk_hub', sa.String(), nullable=True, comment='Hash Key for hub business key'),
        sa.Column('attendance', sa.Float(), nullable=True, comment='crowd attendance'),
        sa.Column('referee', sa.String(), nullable=True, comment='match referee'),
        sa.Column('hs', sa.Float(), nullable=True, comment='home team shots'),
        sa.Column('as', sa.Float(), nullable=True, comment='away team shots'),
        sa.Column('hst', sa.Float(), nullable=True, comment='home team shots on target'),
        sa.Column('ast', sa.Float(), nullable=True, comment='away team shots on target'),
        sa.Column('hhw', sa.Float(), nullable=True, comment='home team hit woodwork'),
        sa.Column('ahw', sa.Float(), nullable=True, comment='away team hit woodwork'),
        sa.Column('hc', sa.Float(), nullable=True, comment='home team corners'),
        sa.Column('ac', sa.Float(), nullable=True, comment='away team corners'),
        sa.Column('hf', sa.Float(), nullable=True, comment='home team fouls committed'),
        sa.Column('af', sa.Float(), nullable=True, comment='away team fouls committed'),
        sa.Column('hfkc', sa.Float(), nullable=True, comment='home team free kicks conceded'),
        sa.Column('afkc', sa.Float(), nullable=True, comment='away team free kicks conceded'),
        sa.Column('ho', sa.Float(), nullable=True, comment='home team offsides'),
        sa.Column('ao', sa.Float(), nullable=True, comment='away team offsides'),
        sa.Column('hy', sa.Float(), nullable=True, comment='home team yellow cards'),
        sa.Column('ay', sa.Float(), nullable=True, comment='away team yellow cards'),
        sa.Column('hr', sa.Float(), nullable=True, comment='home team red cards'),
        sa.Column('ar', sa.Float(), nullable=True, comment='away team red cards'),
        sa.Column('hbp', sa.Float(), nullable=True, comment='home team bookings points (10 = yellow, 25 = red)'),
        sa.Column('abp', sa.Float(), nullable=True, comment='away team bookings points (10 = yellow, 25 = red)'),
        sa.Column('hash_diff', sa.String(), nullable=True, comment='Hash of row'),
        sa.Column('ldts', sa.String(), nullable=True, comment='load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('ulid', name=op.f('pk_sat_matches_core_statistics')),
        schema='main',
    )
    op.create_index(op.f('ix_main_sat_matches_core_statistics_hash_diff'), 'sat_matches_core_statistics', ['hash_diff'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_core_statistics_hk_hub'), 'sat_matches_core_statistics', ['hk_hub'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_core_statistics_ulid'), 'sat_matches_core_statistics', ['ulid'], unique=False, schema='main')
    op.create_table(
        'sat_matches_odds_bet365',
        sa.Column('ulid', sa.String(), nullable=False, comment='ULID id for row'),
        sa.Column('hk_hub', sa.String(), nullable=True, comment='Hash Key for hub business key'),
        sa.Column('b365h', sa.Float(), nullable=True, comment='Bet365 home win odds'),
        sa.Column('b365d', sa.Float(), nullable=True, comment='Bet365 draw odds'),
        sa.Column('b365a', sa.Float(), nullable=True, comment='Bet365 away win odds'),
        sa.Column('b365ch', sa.Float(), nullable=True, comment='Bet365 home win closing odds'),
        sa.Column('b365cd', sa.Float(), nullable=True, comment='Bet365 draw closing odds'),
        sa.Column('b365ca', sa.Float(), nullable=True, comment='Bet365 away win closing odds'),
        sa.Column('b365_over_2_5', sa.Float(), nullable=True, comment='Bet365 over 2.5 goals'),
        sa.Column('b365_under_2_5', sa.Float(), nullable=True, comment='Bet365 under 2.5 goals'),
        sa.Column('hash_diff', sa.String(), nullable=True, comment='Hash of row'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('ulid', name=op.f('pk_sat_matches_odds_bet365')),
        schema='main',
    )
    op.create_index(op.f('ix_main_sat_matches_odds_bet365_hash_diff'), 'sat_matches_odds_bet365', ['hash_diff'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_odds_bet365_hk_hub'), 'sat_matches_odds_bet365', ['hk_hub'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_odds_bet365_ulid'), 'sat_matches_odds_bet365', ['ulid'], unique=False, schema='main')
    op.create_table(
        'sat_matches_odds_market_consensus',
        sa.Column('ulid', sa.String(), nullable=False, comment='ULID id for row'),
        sa.Column('hk_hub', sa.String(), nullable=True, comment='Hash Key for hub business key'),
        sa.Column('maxh', sa.Float(), nullable=True, comment='Market maximum home win odds'),
        sa.Column('maxch', sa.Float(), nullable=True, comment='Market maximum home win closing odds'),
        sa.Column('maxd', sa.Float(), nullable=True, comment='Market maximum draw win odds'),
        sa.Column('maxcd', sa.Float(), nullable=True, comment='Market maximum draw win closing odds'),
        sa.Column('maxa', sa.Float(), nullable=True, comment='Market maximum away win odds'),
        sa.Column('maxca', sa.Float(), nullable=True, comment='Market maximum away win closing odds'),
        sa.Column('avgh', sa.Float(), nullable=True, comment='Market average home win odds'),
        sa.Column('avgch', sa.Float(), nullable=True, comment='Market average home win closing odds'),
        sa.Column('avgd', sa.Float(), nullable=True, comment='Market average draw odds'),
        sa.Column('avgcd', sa.Float(), nullable=True, comment='Market average draw closing odds'),
        sa.Column('avga', sa.Float(), nullable=True, comment='Market average away win odds'),
        sa.Column('avgca', sa.Float(), nullable=True, comment='Market average away win closing odds'),
        sa.Column('max_over_2_5', sa.Float(), nullable=True, comment='Market maximum over 2.5 goals'),
        sa.Column('max_c_over_2_5', sa.Float(), nullable=True, comment='Market maximum over 2.5 goals - closing odds'),
        sa.Column('max_under_2_5', sa.Float(), nullable=True, comment='Market maximum under 2.5 goals'),
        sa.Column('max_c_under_2_5', sa.Float(), nullable=True, comment='Market maximum under 2.5 goals - closing odds'),
        sa.Column('avg_over_2_5', sa.Float(), nullable=True, comment='Market average over 2.5 goals'),
        sa.Column('avg_c_over_2_5', sa.Float(), nullable=True, comment='Market average over 2.5 goals - closing odds'),
        sa.Column('avg_under_2_5', sa.Float(), nullable=True, comment='Market average under 2.5 goals'),
        sa.Column('avg_c_under_2_5', sa.Float(), nullable=True, comment='Market average under 2.5 goals - closing odds'),
        sa.Column('hash_diff', sa.String(), nullable=True, comment='Hash of row'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('ulid', name=op.f('pk_sat_matches_odds_market_consensus')),
        schema='main',
    )
    op.create_index(op.f('ix_main_sat_matches_odds_market_consensus_hash_diff'), 'sat_matches_odds_market_consensus', ['hash_diff'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_odds_market_consensus_hk_hub'), 'sat_matches_odds_market_consensus', ['hk_hub'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_odds_market_consensus_ulid'), 'sat_matches_odds_market_consensus', ['ulid'], unique=False, schema='main')
    op.create_table(
        'sat_matches_odds_sportingbet',
        sa.Column('ulid', sa.String(), nullable=False, comment='ULID id for row'),
        sa.Column('hk_hub', sa.String(), nullable=True, comment='Hash Key for hub business key'),
        sa.Column('sbh', sa.Float(), nullable=True, comment='Sportingbet home win odds'),
        sa.Column('sbd', sa.Float(), nullable=True, comment='Sportingbet draw odds'),
        sa.Column('sba', sa.Float(), nullable=True, comment='Sportingbet away win odds'),
        sa.Column('sbch', sa.Float(), nullable=True, comment='Sportingbet home win closing odds'),
        sa.Column('sbcd', sa.Float(), nullable=True, comment='Sportingbet draw closing odds'),
        sa.Column('sbac', sa.Float(), nullable=True, comment='Sportingbet away win closing odds'),
        sa.Column('hash_diff', sa.String(), nullable=True, comment='Hash of row'),
        sa.Column('ldts', sa.String(), nullable=True, comment='Load timestamp of row'),
        sa.Column('src', sa.String(), nullable=True, comment='Source of data'),
        sa.Column('src_record', sa.String(), nullable=True, comment='Record source of data'),
        sa.PrimaryKeyConstraint('ulid', name=op.f('pk_sat_matches_odds_sportingbet')),
        schema='main',
    )
    op.create_index(op.f('ix_main_sat_matches_odds_sportingbet_hash_diff'), 'sat_matches_odds_sportingbet', ['hash_diff'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_odds_sportingbet_hk_hub'), 'sat_matches_odds_sportingbet', ['hk_hub'], unique=False, schema='main')
    op.create_index(op.f('ix_main_sat_matches_odds_sportingbet_ulid'), 'sat_matches_odds_sportingbet', ['ulid'], unique=False, schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_sat_matches_odds_sportingbet_ulid'), table_name='sat_matches_odds_sportingbet', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_sportingbet_hk_hub'), table_name='sat_matches_odds_sportingbet', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_sportingbet_hash_diff'), table_name='sat_matches_odds_sportingbet', schema='main')
    op.drop_table('sat_matches_odds_sportingbet', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_market_consensus_ulid'), table_name='sat_matches_odds_market_consensus', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_market_consensus_hk_hub'), table_name='sat_matches_odds_market_consensus', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_market_consensus_hash_diff'), table_name='sat_matches_odds_market_consensus', schema='main')
    op.drop_table('sat_matches_odds_market_consensus', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_bet365_ulid'), table_name='sat_matches_odds_bet365', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_bet365_hk_hub'), table_name='sat_matches_odds_bet365', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_odds_bet365_hash_diff'), table_name='sat_matches_odds_bet365', schema='main')
    op.drop_table('sat_matches_odds_bet365', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_core_statistics_ulid'), table_name='sat_matches_core_statistics', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_core_statistics_hk_hub'), table_name='sat_matches_core_statistics', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_core_statistics_hash_diff'), table_name='sat_matches_core_statistics', schema='main')
    op.drop_table('sat_matches_core_statistics', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_core_results_ulid'), table_name='sat_matches_core_results', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_core_results_hk_hub'), table_name='sat_matches_core_results', schema='main')
    op.drop_index(op.f('ix_main_sat_matches_core_results_hash_diff'), table_name='sat_matches_core_results', schema='main')
    op.drop_table('sat_matches_core_results', schema='main')
    op.drop_index(op.f('ix_main_monitor_logs_ulid_thread'), table_name='monitor_logs', schema='main')
    op.drop_index(op.f('ix_main_monitor_logs_source'), table_name='monitor_logs', schema='main')
    op.drop_index(op.f('ix_main_monitor_logs_process'), table_name='monitor_logs', schema='main')
    op.drop_table('monitor_logs', schema='main')
    op.drop_index(op.f('ix_main_lnk_matches_hk_match_season'), table_name='lnk_matches', schema='main')
    op.drop_index(op.f('ix_main_lnk_matches_hk_match_league'), table_name='lnk_matches', schema='main')
    op.drop_index(op.f('ix_main_lnk_matches_hk_match_home_team'), table_name='lnk_matches', schema='main')
    op.drop_index(op.f('ix_main_lnk_matches_hk_match_country'), table_name='lnk_matches', schema='main')
    op.drop_index(op.f('ix_main_lnk_matches_hk_match_away_team'), table_name='lnk_matches', schema='main')
    op.drop_index(op.f('ix_main_lnk_matches_hk'), table_name='lnk_matches', schema='main')
    op.drop_table('lnk_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_teams_hk'), table_name='hub_teams', schema='main')
    op.drop_index(op.f('ix_main_hub_teams_bk'), table_name='hub_teams', schema='main')
    op.drop_table('hub_teams', schema='main')
    op.drop_index(op.f('ix_main_hub_seasons_hk'), table_name='hub_seasons', schema='main')
    op.drop_index(op.f('ix_main_hub_seasons_bk'), table_name='hub_seasons', schema='main')
    op.drop_table('hub_seasons', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_hk'), table_name='hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_bk_match_time'), table_name='hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_bk_match_season'), table_name='hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_bk_match_league'), table_name='hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_bk_match_home_team'), table_name='hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_bk_match_date'), table_name='hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_bk_match_country'), table_name='hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_matches_bk_match_away_team'), table_name='hub_matches', schema='main')
    op.drop_table('hub_matches', schema='main')
    op.drop_index(op.f('ix_main_hub_leagues_hk'), table_name='hub_leagues', schema='main')
    op.drop_index(op.f('ix_main_hub_leagues_bk'), table_name='hub_leagues', schema='main')
    op.drop_table('hub_leagues', schema='main')
    # ### end Alembic commands ###
